target-version = "py312"
exclude = [
    "**/*_pb2.py",        # Exclude protobuf-generated Python files
    "**/*_pb2_grpc.py",   # Exclude protobuf-generated gRPC Python files
    "**/*_pb2.pyi",       # Exclude protobuf-generated type stub files
]

[lint]
select = [
    "A",        # flake8-builtins
    "B",        # flake8-bugbear
    "BLE",      # flake8-blind-except
    "C4",       # flake8-comprehensions
    "C9",       # mccabe
    "E", "W",   # pycodestyle
    "F",        # pyflakes
    "FBT",      # flake8-boolean-trap
    "I",        # isort
    "ISC",      # flake8-implicit-str-concat
    "N",        # pep8-naming
    "PL",       # pylint
    "RUF",      # Ruff specific rules
]
fixable = ["ALL"]
ignore = ["E501"]  # Never enforce `E501` (line length violations)

[lint.per-file-ignores]
"**/server.py" = ["N802"]
"**/client.py" = ["N802"]

[format]
exclude = [
    "**/*_pb2.py",        # Exclude protobuf-generated Python files
    "**/*_pb2_grpc.py",   # Exclude protobuf-generated gRPC Python files
    "**/*_pb2.pyi",       # Exclude protobuf-generated type stub files
]
