# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld2.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'helloworld2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11helloworld2.proto\x12\x0bhelloworld2\"\x0f\n\rRecipeRequest\">\n\x06Recipe\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bingredients\x18\x02 \x01(\t\x12\x11\n\tmeal_type\x18\x03 \x01(\t\"&\n\x0eTimeStampReply\x12\x14\n\x0c\x63urrent_time\x18\x01 \x01(\t\"\x1f\n\x0bTimeRequest\x12\x10\n\x08timezone\x18\x01 \x01(\t2\x8c\x01\n\rHealthyRecipe\x12>\n\tBreakfast\x12\x1a.helloworld2.RecipeRequest\x1a\x13.helloworld2.Recipe\"\x00\x12;\n\x06\x44inner\x12\x1a.helloworld2.RecipeRequest\x1a\x13.helloworld2.Recipe\"\x00\x32O\n\rWhatIsTheTime\x12>\n\x03Now\x12\x18.helloworld2.TimeRequest\x1a\x1b.helloworld2.TimeStampReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECIPEREQUEST']._serialized_start=34
  _globals['_RECIPEREQUEST']._serialized_end=49
  _globals['_RECIPE']._serialized_start=51
  _globals['_RECIPE']._serialized_end=113
  _globals['_TIMESTAMPREPLY']._serialized_start=115
  _globals['_TIMESTAMPREPLY']._serialized_end=153
  _globals['_TIMEREQUEST']._serialized_start=155
  _globals['_TIMEREQUEST']._serialized_end=186
  _globals['_HEALTHYRECIPE']._serialized_start=189
  _globals['_HEALTHYRECIPE']._serialized_end=329
  _globals['_WHATISTHETIME']._serialized_start=331
  _globals['_WHATISTHETIME']._serialized_end=410
# @@protoc_insertion_point(module_scope)
